[package]
name = "git-testament"
version = "0.1.0"
authors = ["Daniel Silverstone <dsilvers@digital-scurf.org>"]
edition = "2018"

[workspace]
members = [
    "git-testament-derive",
    "test-template"
]

[dependencies]
git-testament-derive = { path = "git-testament-derive" }