[package]
authors = ["Daniel Silverstone <dsilvers@digital-scurf.org>"]
edition = "2018"
name = "git-testament-derive"
version = "0.1.0"
[dependencies]
syn = "0.15"
quote = "0.6"
git2 = "0.8"
chrono = "0.4"
log = "0.4"

[lib]
proc-macro = true
